(()=>{
const careerPaths=[
 {id:'stable',icon:'🏢',name:'Stable Operator',desc:'Structured role, reliable salary, slower experimentation.',salary:32,skill:38,stress:28,reputation:36,traits:{security:4,growth:1,freedom:0}},
 {id:'growth',icon:'🚀',name:'Growth Track',desc:'Lower starting pay, faster learning, more ownership and deadline pressure.',salary:22,skill:48,stress:42,reputation:32,traits:{security:1,growth:4,freedom:2}},
 {id:'network',icon:'🌐',name:'Tech Support → Network',desc:'Build technical depth, certifications and problem-solving credibility.',salary:26,skill:44,stress:34,reputation:34,traits:{security:3,growth:3,freedom:1}},
 {id:'pharma',icon:'💊',name:'Pharma Career',desc:'Use your degree path, gain domain experience, then specialize or move abroad.',salary:25,skill:42,stress:31,reputation:38,traits:{security:3,growth:2,freedom:1}}
];
const events=[
 {title:'Month 3 — Your manager gives you repetitive work',text:'You are reliable, but your learning curve is flattening.',choices:[
  {t:'Ask for one harder responsibility',s:'Keep your current job while creating a stretch opportunity.',d:{skill:8,stress:3,reputation:6,salary:0},xp:16,n:'You increase your surface area for growth.'},
  {t:'Stay quiet and master the routine',s:'Become extremely dependable before asking for more.',d:{skill:3,stress:-3,reputation:5,salary:1},xp:11,n:'Reliability rises, but your growth rate stays moderate.'},
  {t:'Start preparing to switch immediately',s:'Use evenings to build a stronger exit option.',d:{skill:6,stress:6,reputation:-1,salary:3},xp:14,n:'You create optionality, but split your attention.'}
 ]},
 {title:'Month 8 — A project is failing near deadline',text:'Nobody clearly owns the problem and the team is becoming defensive.',choices:[
  {t:'Take ownership and organize a recovery plan',s:'Break the problem into tasks and assign clear owners.',d:{skill:6,stress:8,reputation:9,salary:1},xp:18,n:'High agency makes you visible, but responsibility carries pressure.'},
  {t:'Only finish your assigned part',s:'Avoid becoming responsible for everyone else’s mistakes.',d:{skill:2,stress:-2,reputation:1,salary:0},xp:9,n:'You protect yourself, but miss a leadership signal.'},
  {t:'Escalate the issue early with evidence',s:'Show what is blocked and what decision is needed.',d:{skill:4,stress:2,reputation:7,salary:0},xp:16,n:'Clear escalation is often stronger than silent heroics.'}
 ]},
 {title:'Year 1 — You get a better offer',text:'The new role pays more, but the company is less stable and expects faster output.',choices:[
  {t:'Switch for the higher-growth role',s:'Accept more uncertainty for faster progression.',d:{skill:9,stress:9,reputation:4,salary:10},xp:20,n:'You trade stability for a steeper trajectory.'},
  {t:'Stay and negotiate using the offer',s:'Try to improve pay without losing your current stability.',d:{skill:2,stress:3,reputation:5,salary:6},xp:18,n:'You use leverage while limiting downside.'},
  {t:'Stay without negotiating',s:'Keep the known environment and avoid unnecessary risk.',d:{skill:1,stress:-5,reputation:2,salary:1},xp:10,n:'Your stress stays lower, but your market leverage expires.'}
 ]},
 {title:'Year 2 — You have enough experience to specialize',text:'You can deepen one skill, move toward management, or build something independently.',choices:[
  {t:'Become a specialist',s:'Choose a valuable niche and build rare technical/domain depth.',d:{skill:12,stress:4,reputation:8,salary:7},xp:20,n:'Depth increases your value and makes your profile easier to differentiate.'},
  {t:'Move toward leadership',s:'Improve communication, planning and people management.',d:{skill:6,stress:7,reputation:11,salary:6},xp:19,n:'Your value shifts from doing work to multiplying other people’s work.'},
  {t:'Build a side business after work',s:'Keep income while testing independence in small steps.',d:{skill:8,stress:11,reputation:4,salary:5},xp:20,n:'You create a second path without immediately destroying your safety net.'}
 ]},
 {title:'Year 3 — Your career is working, but you feel the trade-offs',text:'Your next move should match what you value now, not what sounded impressive three years ago.',choices:[
  {t:'Optimize for income and progression',s:'Push for higher-value roles and measurable career growth.',d:{skill:6,stress:7,reputation:8,salary:12},xp:18,n:'You maximize career momentum, with a higher pressure ceiling.'},
  {t:'Optimize for balance and sustainability',s:'Protect time, health and predictable workload.',d:{skill:3,stress:-12,reputation:3,salary:3},xp:16,n:'A sustainable career can compound longer than a constantly exhausted one.'},
  {t:'Prepare a deliberate exit into your own work',s:'Save runway, validate demand, then leave only when the numbers make sense.',d:{skill:8,stress:5,reputation:5,salary:5},xp:20,n:'You convert independence from a fantasy into a staged decision.'}
 ]}
];
let c={path:null,i:0,salary:0,skill:0,stress:0,reputation:0,xp:0,timeline:[]};
const $=id=>document.getElementById(id);
function open(){c={path:null,i:0,salary:0,skill:0,stress:0,reputation:0,xp:0,timeline:[]};$('careerSim').classList.add('open');$('careerSim').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';renderStart()}
function close(){$('careerSim').classList.remove('open');$('careerSim').setAttribute('aria-hidden','true');document.body.style.overflow=''}
function renderStart(){$('careerStep').textContent='START';$('careerContent').innerHTML=`<article class="career-panel glass"><span class="career-chip">💼 CAREER SIMULATOR</span><h2 class="career-title">Choose your starting path</h2><p class="career-sub">This is not a “best career” quiz. You will experience trade-offs between money, learning, stress, reputation and freedom over three simulated years.</p></article><div class="career-grid">${careerPaths.map(p=>`<button class="career-option" data-path="${p.id}"><span class="career-icon">${p.icon}</span><span><b>${p.name}</b><small>${p.desc}</small></span></button>`).join('')}</div>`;document.querySelectorAll('[data-path]').forEach(b=>b.onclick=()=>choosePath(b.dataset.path))}
function choosePath(id){const p=careerPaths.find(x=>x.id===id);c.path=p;c.salary=p.salary;c.skill=p.skill;c.stress=p.stress;c.reputation=p.reputation;c.timeline.push({icon:p.icon,title:`Started: ${p.name}`,text:p.desc});renderEvent()}
function hud(){return `<div class="career-hud"><div class="career-stat"><span>INCOME INDEX</span><b>₹ ${c.salary}K</b></div><div class="career-stat"><span>SKILL</span><b>${c.skill}</b></div><div class="career-stat"><span>STRESS</span><b>${c.stress}</b></div><div class="career-stat"><span>REPUTATION</span><b>${c.reputation}</b></div></div>`}
function renderEvent(){const e=events[c.i];$('careerStep').textContent=`${c.i+1} / ${events.length}`;$('careerContent').innerHTML=`${hud()}<article class="career-event glass"><span class="career-chip">CAREER EVENT</span><h3>${e.title}</h3><p class="career-sub">${e.text}</p></article><div class="career-grid">${e.choices.map((x,i)=>`<button class="career-option" data-career-choice="${i}"><span class="career-icon">${['A','B','C'][i]}</span><span><b>${x.t}</b><small>${x.s}</small></span></button>`).join('')}</div>`;document.querySelectorAll('[data-career-choice]').forEach(b=>b.onclick=()=>choose(Number(b.dataset.careerChoice)))}
function choose(i){const e=events[c.i],x=e.choices[i];Object.entries(x.d).forEach(([k,v])=>c[k]=Math.max(0,c[k]+v));c.xp+=x.xp;c.timeline.push({icon:'›',title:e.title,text:x.t});$('careerContent').innerHTML=`${hud()}<article class="career-result glass"><p class="eyebrow">CONSEQUENCE</p><h3>${x.n}</h3><p class="career-sub">${x.s}</p><div class="career-delta">${Object.entries(x.d).filter(([,v])=>v!==0).map(([k,v])=>`<span class="career-pill">${k.toUpperCase()} ${v>0?'+':''}${v}</span>`).join('')}<span class="career-pill">XP +${x.xp}</span></div><button id="careerNext" class="primary-action">${c.i===events.length-1?'See 3-year outcome →':'Continue career →'}</button></article>`;$('careerNext').onclick=()=>{c.i++;c.i>=events.length?summary():renderEvent()}}
function summary(){const score=Math.round(c.skill*.32+c.reputation*.28+c.salary*.7-Math.max(0,c.stress-45)*.25);let label='Balanced Builder',text='You built a career with a reasonable mix of growth, stability and optionality.';if(c.skill>=72&&c.reputation>=62){label='High-Value Operator';text='You repeatedly chose learning, ownership and market value. Your main risk is carrying too much pressure for too long.'}else if(c.stress<=30){label='Sustainable Strategist';text='You protected sustainability and avoided letting career progress consume everything else.'}else if(c.salary>=58){label='Momentum Chaser';text='You pushed strongly toward income and progression. Your next challenge is making the trajectory sustainable.'}else if(c.timeline.some(t=>/own work|side business|exit/i.test(t.text))){label='Independent Pathfinder';text='You are building optionality toward independence instead of making a blind jump.'}
 $('careerStep').textContent='RESULT';$('careerContent').innerHTML=`<article class="career-summary glass"><p class="eyebrow">3-YEAR SIMULATION COMPLETE</p><div class="summary-orb">💼</div><h2>${label}</h2><p class="career-sub">${text}</p><div class="career-score">Career score ${score}</div><div class="career-bars">${[['Income',Math.min(100,c.salary)],['Skill',Math.min(100,c.skill)],['Stress',Math.min(100,c.stress)],['Reputation',Math.min(100,c.reputation)]].map(([n,v])=>`<div class="career-bar"><span>${n}</span><div class="career-meter"><i style="width:${v}%"></i></div><b>${v}</b></div>`).join('')}</div><div class="career-timeline">${c.timeline.map(t=>`<div class="timeline-row"><span>${t.icon}</span><div><b>${t.title}</b><small>${t.text}</small></div></div>`).join('')}</div><p class="career-sub">Session reward: <b>+${c.xp} XP</b></p><div class="career-actions"><button id="careerReplay" class="career-secondary">Replay</button><button id="careerFinish" class="primary-action">Collect XP</button></div></article>`;$('careerReplay').onclick=renderStart;$('careerFinish').onclick=finish}
function finish(){try{const key='evolve-v01';const s=JSON.parse(localStorage.getItem(key)||'{}');s.totalXP=(s.totalXP||0)+c.xp;s.careerSessions=(s.careerSessions||0)+1;s.stats=s.stats||{};s.stats.INT=Math.min(100,(s.stats.INT||12)+2);s.stats.FIN=Math.min(100,(s.stats.FIN||9)+2);s.stats.DISC=Math.min(100,(s.stats.DISC||11)+1);localStorage.setItem(key,JSON.stringify(s));if(typeof state!=='undefined'){state.totalXP=s.totalXP;state.careerSessions=s.careerSessions;state.stats={...state.stats,...s.stats};if(typeof render==='function')render()}close();if(typeof toast==='function')toast(`Career Sim +${c.xp} XP`)}catch(e){close()}}
window.openCareerSim=open;
document.addEventListener('DOMContentLoaded',()=>{const closeBtn=$('closeCareer');if(closeBtn)closeBtn.onclick=close;document.querySelectorAll('.module-card').forEach(card=>{if(card.dataset.module==='Career Sim'){card.addEventListener('click',ev=>{ev.stopImmediatePropagation();open()},true)}})})
})();