const englishScenarioBank=[
  {tier:1,avatar:'🧑‍💼',role:'Interviewer',prompt:'Tell me about yourself in a job interview.',goal:'Give a clear 30–60 second introduction: who you are, what you do, one strength, and what you want next.',keywords:['student','learn','skill','experience','goal'],model:'I’m a student who enjoys learning practical skills and solving problems. I’m still early in my career, but I learn quickly and I’m looking for an opportunity where I can build strong real-world experience.'},
  {tier:1,avatar:'☕',role:'Café staff',prompt:'Your order is wrong. Explain the problem politely and ask for a replacement.',goal:'Be direct without sounding rude. State the issue, then make a clear request.',keywords:['ordered','instead','could','please','replace'],model:'Excuse me, I think there may have been a small mix-up. I ordered a cold coffee, but I received a hot one. Could you please replace it?'},
  {tier:1,avatar:'🧑',role:'New person',prompt:'Start a natural conversation with someone you have just met at an event.',goal:'Open simply, ask an easy question, and give them something to respond to.',keywords:['hi','name','here','what','how'],model:'Hey, I’m N S H D. I don’t think we’ve met before. How do you know the people here?'},
  {tier:1,avatar:'📞',role:'Receptionist',prompt:'Call a clinic and ask for an appointment tomorrow afternoon.',goal:'Say why you are calling, ask clearly for a time, and confirm what is available.',keywords:['appointment','tomorrow','afternoon','available','please'],model:'Hi, I’d like to book an appointment for tomorrow afternoon if possible. Could you tell me what times are available?'},
  {tier:1,avatar:'🛍️',role:'Shop staff',prompt:'Ask whether a product is available in another size and price range.',goal:'Ask one clear question at a time and keep the request specific.',keywords:['size','available','price','another','looking'],model:'Hi, I’m looking for this in a larger size. Do you have it available, and is the price the same?'},
  {tier:2,avatar:'👥',role:'Class group',prompt:'You disagree with the plan your group has chosen. Explain your alternative.',goal:'Disagree respectfully, give a reason, and suggest a practical next step.',keywords:['think','because','suggest','instead','better'],model:'I understand why we chose this plan, but I think we may run into a time problem. I’d suggest splitting the work into two smaller parts and testing the first part today.'},
  {tier:2,avatar:'🎓',role:'Teacher',prompt:'You did not understand part of a lecture. Ask for clarification without sounding lost.',goal:'Mention the exact part you understood and the point you need explained again.',keywords:['understood','part','could','explain','again'],model:'I understood the first part about the mechanism, but I’m not clear on why the second step happens. Could you explain that part once more?'},
  {tier:2,avatar:'🤝',role:'Teammate',prompt:'A teammate has missed a deadline. Ask what happened and get a new commitment.',goal:'Stay calm, describe the problem, and ask for a specific next step.',keywords:['deadline','need','when','finish','plan'],model:'We needed this by today and it is still pending. Is something blocking you? When can you realistically finish it so we can adjust the rest of the plan?'},
  {tier:2,avatar:'🧑‍💼',role:'Supervisor',prompt:'Ask your manager for more challenging work without sounding dissatisfied.',goal:'Show reliability first, then ask for one concrete growth opportunity.',keywords:['completed','responsibility','learn','project','opportunity'],model:'I’m comfortable with my current tasks and I’ve been completing them consistently. I’d like to take on one more challenging responsibility so I can learn faster. Is there a project I could support?'},
  {tier:2,avatar:'🗣️',role:'Friend',prompt:'A friend misunderstood something you said. Clear it up without becoming defensive.',goal:'Acknowledge the misunderstanding, explain your intention, and keep the tone calm.',keywords:['meant','understand','sorry','intention','clear'],model:'I can see why that sounded different from what I meant. I wasn’t trying to criticize you. What I meant was that the timing might be difficult, not that your idea was bad.'},
  {tier:3,avatar:'💼',role:'Interviewer',prompt:'You are asked: “Why should we choose you when you have less experience than other candidates?”',goal:'Answer confidently without pretending to have experience you do not have.',keywords:['experience','learn','quickly','strength','contribute'],model:'I may have less experience, but I learn quickly, I prepare seriously, and I’m comfortable asking questions when I need clarity. I can bring strong effort and adaptability while building the experience I still need.'},
  {tier:3,avatar:'💰',role:'Client',prompt:'A client says your price is too high. Defend your value without sounding arrogant.',goal:'Acknowledge the concern, explain value, and offer one practical option.',keywords:['understand','price','value','includes','option'],model:'I understand the price is higher than some alternatives. It includes the full design, revisions, and delivery-ready files. If budget is the main issue, I can reduce the scope while keeping the core result.'},
  {tier:3,avatar:'⚠️',role:'Team lead',prompt:'You made a visible mistake that affected the team. Explain it and propose a recovery plan.',goal:'Own the mistake clearly, avoid excuses, and state what you will do next.',keywords:['mistake','responsibility','fix','next','prevent'],model:'I made the mistake and I should have checked it before sending it. I’ve already started correcting it, and I’ll add a final review step so the same issue does not happen again.'},
  {tier:3,avatar:'🎤',role:'Audience',prompt:'Explain a difficult idea you know well to a beginner in under one minute.',goal:'Use one simple definition, one example, and avoid unnecessary jargon.',keywords:['means','simple','example','basically','because'],model:'A computer network is simply a group of devices connected so they can share information. For example, your phone and laptop can both use the same Wi-Fi router to communicate with the internet.'},
  {tier:3,avatar:'🧭',role:'Senior colleague',prompt:'Someone gives you harsh feedback in front of others. Respond professionally in the moment.',goal:'Stay composed, acknowledge the useful point, and move the deeper discussion to a better setting.',keywords:['understand','feedback','discuss','after','improve'],model:'I understand the point you’re making. I’d like to fix it properly, so can we discuss the details after this meeting and go through what needs to change?'}
];
let englishScenarios=[],englishIndex=0,englishTotals={clarity:0,grammar:0,confidence:0},englishXP=0,recognition=null,englishRunTier=1;
function readEnglishState(){try{return JSON.parse(localStorage.getItem('evolve-v01')||'{}')}catch{return{}}}
function chooseEnglishScenarios(){const s=readEnglishState(),runs=+(s.englishSessions||s.englishRuns||0);englishRunTier=runs>=8?3:runs>=3?2:1;const pool=englishScenarioBank.filter(x=>x.tier<=englishRunTier),copy=[...pool].sort(()=>Math.random()-.5);return copy.slice(0,5)}
function openEnglishArena(){englishScenarios=chooseEnglishScenarios();englishIndex=0;englishTotals={clarity:0,grammar:0,confidence:0};englishXP=0;const s=document.getElementById('englishArena');s.classList.add('open');s.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';renderEnglish();}
function closeEnglishArena(){const s=document.getElementById('englishArena');s.classList.remove('open');s.setAttribute('aria-hidden','true');document.body.style.overflow='';if(recognition){try{recognition.stop()}catch{}}}
function renderEnglish(){const s=englishScenarios[englishIndex];document.getElementById('englishProgress').textContent=`${englishIndex+1} / ${englishScenarios.length}`;document.getElementById('englishAvatar').textContent=s.avatar;document.getElementById('englishRole').textContent=s.role;document.getElementById('englishPrompt').textContent=s.prompt;document.getElementById('englishGoal').textContent=s.goal;document.getElementById('englishResponse').value='';document.getElementById('englishResult').hidden=true;document.getElementById('englishSummary').hidden=true;document.getElementById('englishInputCard').hidden=false;let badge=document.getElementById('englishTierBadge');if(!badge){badge=document.createElement('span');badge.id='englishTierBadge';badge.className='english-tier-badge';document.querySelector('.english-card')?.prepend(badge)}badge.textContent=`${englishRunTier===1?'STARTER':englishRunTier===2?'MEDIUM':'HARD'} SPEAKING`;document.getElementById('englishArena').scrollTo({top:0,behavior:'smooth'});}
function scoreEnglish(text){const cleaned=text.trim(),words=cleaned?cleaned.split(/\s+/):[],lower=cleaned.toLowerCase(),fillers=(lower.match(/\b(um|uh|like|actually|basically|you know|i mean)\b/g)||[]).length,sentences=(cleaned.match(/[.!?]+/g)||[]).length||1,scenario=englishScenarios[englishIndex],hits=scenario.keywords.filter(k=>lower.includes(k)).length,hedges=(lower.match(/\b(maybe|probably|i guess|not sure|kind of|sort of)\b/g)||[]).length,repeats=(lower.match(/\b(\w+)\s+\1\b/g)||[]).length;let clarity=Math.round(Math.min(100,32+Math.min(words.length,55)*1.05+hits*5-fillers*6-repeats*4)),grammar=Math.round(Math.min(100,44+Math.min(sentences,5)*6+(cleaned[0]&&cleaned[0]===cleaned[0].toUpperCase()?5:0)-fillers*2)),confidence=Math.round(Math.min(100,30+Math.min(words.length,45)*1.1+hits*6-hedges*5));clarity=Math.max(15,clarity);grammar=Math.max(20,grammar);confidence=Math.max(15,confidence);return{clarity,grammar,confidence,fillers,words:words.length,hits,hedges,repeats}}
function submitEnglish(){const text=document.getElementById('englishResponse').value.trim();if(text.length<8){toast('Say or type a little more first');return}const sc=scoreEnglish(text);englishTotals.clarity+=sc.clarity;englishTotals.grammar+=sc.grammar;englishTotals.confidence+=sc.confidence;const avg=Math.round((sc.clarity+sc.grammar+sc.confidence)/3),earned=Math.max(8,Math.round(avg/7)+(englishRunTier-1)*2);englishXP+=earned;document.getElementById('englishInputCard').hidden=true;document.getElementById('englishResult').hidden=false;document.getElementById('clarityScore').textContent=sc.clarity;document.getElementById('grammarScore').textContent=sc.grammar;document.getElementById('confidenceScore').textContent=sc.confidence;let feedback=[];if(sc.words<15)feedback.push('Add one more complete idea so your answer feels less abrupt.');else if(sc.words>70)feedback.push('Tighten the answer; shorter sentences will make it easier to follow.');else feedback.push('Your response length is in a useful conversational range.');if(sc.fillers>1)feedback.push(`Reduce filler words — about ${sc.fillers} were detected.`);else feedback.push('Good control of filler words.');if(sc.hedges>1)feedback.push('Use slightly more decisive wording where you already know what you mean.');if(sc.hits<2)feedback.push('Make the purpose of your answer more explicit with one concrete detail.');else feedback.push('You included useful context for the situation.');document.getElementById('englishFeedback').innerHTML=`<b>Local feedback</b>${feedback.join(' ')}`;document.getElementById('englishModel').innerHTML=`<b>Stronger example</b>${englishScenarios[englishIndex].model}`;document.getElementById('englishEarned').textContent=`+${earned} XP this round`}
function nextEnglish(){if(englishIndex<englishScenarios.length-1){englishIndex++;renderEnglish()}else showEnglishSummary()}
function showEnglishSummary(){document.getElementById('englishInputCard').hidden=true;document.getElementById('englishResult').hidden=true;document.getElementById('englishSummary').hidden=false;const n=englishScenarios.length,scores={clarity:Math.round(englishTotals.clarity/n),grammar:Math.round(englishTotals.grammar/n),confidence:Math.round(englishTotals.confidence/n)},ranked=Object.entries(scores).sort((a,b)=>b[1]-a[1]),labels={clarity:['Clear Communicator','Your strongest area is getting the main idea across without too much confusion.'],grammar:['Structured Speaker','Your responses tend to be organized and grammatically controlled.'],confidence:['Confident Speaker','Your wording tends to sound decisive and socially comfortable.']};document.getElementById('englishProfileLabel').textContent=labels[ranked[0][0]][0];document.getElementById('englishProfileSummary').textContent=`${labels[ranked[0][0]][1]} ${englishRunTier===3?'You completed a hard speaking set. ':''}Session reward: ${englishXP} XP.`;document.getElementById('englishBars').innerHTML=Object.entries(scores).map(([k,v])=>`<div class="english-bar"><span>${k.toUpperCase()}</span><div class="english-meter"><i style="width:${v}%"></i></div><b>${v}</b></div>`).join('');document.getElementById('englishArena').scrollTo({top:0,behavior:'smooth'})}
function finishEnglish(){const s=readEnglishState();s.totalXP=(s.totalXP||0)+englishXP;s.englishSessions=(s.englishSessions||0)+1;s.stats=s.stats||{};s.stats.CHA=Math.min(100,(s.stats.CHA||10)+3);s.stats.SOC=Math.min(100,(s.stats.SOC||10)+1);localStorage.setItem('evolve-v01',JSON.stringify(s));closeEnglishArena();location.reload()}
function startVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toast('Voice input is not supported in this browser');return}if(recognition){try{recognition.stop()}catch{}recognition=null}recognition=new SR();recognition.lang='en-IN';recognition.interimResults=true;recognition.continuous=false;const btn=document.getElementById('voiceBtn');btn.classList.add('listening');btn.textContent='● Listening…';let finalText='';recognition.onresult=e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript;if(e.results[i].isFinal)finalText+=t+' ';else interim+=t}document.getElementById('englishResponse').value=(finalText+interim).trim()};recognition.onend=()=>{btn.classList.remove('listening');btn.textContent='🎙 Speak'};recognition.onerror=()=>{btn.classList.remove('listening');btn.textContent='🎙 Speak';toast('Could not capture speech — try typing instead')};try{recognition.start()}catch{toast('Microphone could not start')}}
const oldEnglishCard=document.querySelector('.module-card[data-module="English Arena"]');if(oldEnglishCard){const fresh=oldEnglishCard.cloneNode(true);oldEnglishCard.replaceWith(fresh);fresh.addEventListener('click',openEnglishArena)}
document.getElementById('closeEnglish').addEventListener('click',closeEnglishArena);document.getElementById('englishSubmit').addEventListener('click',submitEnglish);document.getElementById('nextEnglish').addEventListener('click',nextEnglish);document.getElementById('finishEnglish').addEventListener('click',finishEnglish);document.getElementById('voiceBtn').addEventListener('click',startVoice);const englishStyle=document.createElement('style');englishStyle.textContent='.english-tier-badge{display:inline-flex;margin:0 0 10px;padding:5px 8px;border-radius:999px;border:1px solid var(--line);font-size:8px;font-weight:900;letter-spacing:.1em;color:var(--muted);background:rgba(127,127,127,.07)}';document.head.appendChild(englishStyle);