(()=>{
const STORAGE_KEY='evolve-v01';
const scenes=[
 {person:'Classmate',avatar:'🙂',context:'You say something in a group and one classmate smiles, but gives only a short reply. Later they talk normally with someone else.',question:'What is the safest interpretation?',signals:['smiled','short reply','normal with others'],choices:[
  {t:'They dislike me',s:'Their short reply is proof they are avoiding me.',score:1,traits:{awareness:0,confidence:-1,empathy:0},out:'Too certain from weak evidence',text:'A short reply can mean many things. One moment is not enough to conclude rejection.',insight:'Separate facts from the story your mind adds.'},
  {t:'They may have been distracted',s:'The smile matters, and the short reply alone is ambiguous.',score:4,traits:{awareness:3,confidence:1,empathy:2},out:'Balanced read',text:'You notice the positive cue without over-reading the limited response.',insight:'Strong social reading uses multiple cues, not one isolated signal.'},
  {t:'They definitely like me',s:'The smile is a clear sign of attraction.',score:1,traits:{awareness:-1,confidence:1,empathy:0},out:'Overconfident interpretation',text:'A smile can signal friendliness, politeness, comfort or attraction. Context is still missing.',insight:'Do not upgrade a possibility into certainty.'},
  {t:'I should immediately ask what is wrong',s:'Directly confront the change before it becomes awkward.',score:2,traits:{awareness:1,confidence:2,empathy:0},out:'Direct, but premature',text:'Directness is useful when there is a pattern. Here, the evidence is still thin.',insight:'Clarity is good; timing matters too.'}
 ]},
 {person:'Friend',avatar:'🧑',context:'A close friend usually replies quickly. Today they leave your message unread for hours, then respond normally without explaining.',question:'What should you do next?',signals:['unusual delay','normal response','no conflict'],choices:[
  {t:'Act normal unless a pattern appears',s:'One unusual delay does not require a confrontation.',score:4,traits:{awareness:3,confidence:2,empathy:2},out:'Low-drama confidence',text:'You protect the friendship from unnecessary tension while staying observant.',insight:'Patterns deserve conclusions; single events usually deserve curiosity.'},
  {t:'Reply dryly to match them',s:'Show that you noticed the delay.',score:1,traits:{awareness:0,confidence:-1,empathy:-1},out:'Defensive mirroring',text:'Matching imagined distance can create the exact tension you were afraid of.',insight:'Do not punish people for explanations you invented.'},
  {t:'Ask mutual friends what happened',s:'Gather information without asking directly.',score:2,traits:{awareness:1,confidence:-1,empathy:0},out:'Indirect information gathering',text:'You may get context, but you also risk turning a small issue into group gossip.',insight:'Private uncertainty is usually best handled privately.'},
  {t:'Send several follow-up messages',s:'Make sure they did not miss your message.',score:1,traits:{awareness:0,confidence:-2,empathy:0},out:'Anxiety takes control',text:'Repeated checking can create pressure when there may be no problem at all.',insight:'Confidence often looks like tolerating temporary uncertainty.'}
 ]},
 {person:'Group project teammate',avatar:'👥',context:'During a discussion, one teammate keeps interrupting you but also interrupts everyone else. Their tone is fast, not hostile.',question:'How do you read the behaviour?',signals:['interrupts everyone','fast tone','no insults'],choices:[
  {t:'They specifically disrespect me',s:'Interrupting is a dominance move directed at me.',score:1,traits:{awareness:-1,confidence:0,empathy:0},out:'Personalized too quickly',text:'Because they interrupt everyone, the behaviour is more likely a communication habit than a targeted attack.',insight:'Compare how someone treats you with how they treat everyone else.'},
  {t:'They are probably an impulsive communicator',s:'The pattern is broad, so I can set a boundary without making it personal.',score:4,traits:{awareness:3,confidence:2,empathy:2},out:'Context-aware read',text:'You identify the pattern while still protecting your chance to speak.',insight:'Good social intelligence combines interpretation with boundaries.'},
  {t:'I should stay quiet',s:'Avoid creating tension in the group.',score:1,traits:{awareness:1,confidence:-2,empathy:1},out:'Peace at your expense',text:'Avoiding conflict can be useful, but repeatedly disappearing from the conversation is not a healthy solution.',insight:'A calm boundary is not the same thing as an argument.'},
  {t:'Interrupt them back harder',s:'Match their style so they understand.',score:2,traits:{awareness:0,confidence:2,empathy:-1},out:'Escalation instead of boundary',text:'You may get speaking space, but the group communication quality gets worse.',insight:'Assertiveness works better when it is controlled.'}
 ]},
 {person:'New person',avatar:'✨',context:'Someone you recently met asks you questions, remembers a small detail you mentioned, and starts conversations twice this week.',question:'What can you reasonably conclude?',signals:['asks questions','remembers details','initiates twice'],choices:[
  {t:'They are interested in interacting with me',s:'There is repeated engagement, but I do not need to label it further yet.',score:4,traits:{awareness:3,confidence:2,empathy:2},out:'Evidence-based confidence',text:'Repeated initiative is meaningful. You recognize interest without guessing exactly what kind.',insight:'Notice genuine positive signals without forcing a romantic or negative story.'},
  {t:'They definitely have romantic feelings',s:'Remembering details proves attraction.',score:2,traits:{awareness:0,confidence:2,empathy:0},out:'Possible, not proven',text:'Attraction is one explanation, but friendliness and curiosity also fit the evidence.',insight:'Be confident about the signal, modest about the interpretation.'},
  {t:'They are only being polite',s:'Assume nothing positive so I do not get disappointed.',score:2,traits:{awareness:0,confidence:-2,empathy:1},out:'Protective pessimism',text:'Ignoring repeated positive behaviour is also a bias.',insight:'Under-reading can distort reality just as much as over-reading.'},
  {t:'I should test them by becoming distant',s:'See whether they chase me.',score:1,traits:{awareness:-1,confidence:-1,empathy:-1},out:'Games reduce clarity',text:'Artificial distance creates noisy data and can damage a naturally developing connection.',insight:'Healthy social confidence does not need hidden tests.'}
 ]},
 {person:'Senior / authority',avatar:'🧭',context:'A senior gives you blunt feedback: “This needs more work.” They then spend ten minutes showing you what to fix.',question:'What is the strongest read?',signals:['blunt words','gives time','specific help'],choices:[
  {t:'They think I am incompetent',s:'The criticism means they have a low opinion of me.',score:1,traits:{awareness:-1,confidence:-2,empathy:0},out:'Criticism became identity',text:'The extra time and specific help are evidence that they expect improvement, not necessarily failure.',insight:'Feedback about work is not automatically a judgment of your worth.'},
  {t:'The delivery is blunt, but the intent looks constructive',s:'Use the useful information and judge the pattern over time.',score:4,traits:{awareness:3,confidence:2,empathy:2},out:'Emotionally steady read',text:'You distinguish tone from intent and keep access to useful feedback.',insight:'Social maturity means reading behaviour as a whole.'},
  {t:'I should defend every decision I made',s:'Make sure they know I had reasons.',score:2,traits:{awareness:1,confidence:1,empathy:-1},out:'Defensiveness blocks learning',text:'Explaining context can help, but defending everything makes feedback harder to use.',insight:'Confidence can absorb criticism without collapsing or fighting.'},
  {t:'I should avoid them next time',s:'Reduce chances of being criticized again.',score:1,traits:{awareness:0,confidence:-2,empathy:0},out:'Avoidance protects comfort',text:'You avoid discomfort, but also lose mentorship and information.',insight:'Growth often requires staying present through uncomfortable feedback.'}
 ]}
];
let idx=0,xp=0,score=0,traits={awareness:0,confidence:0,empathy:0};
const $=id=>document.getElementById(id);
function readState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{}}catch{return{}}}
function writeState(s){localStorage.setItem(STORAGE_KEY,JSON.stringify(s))}
function open(){idx=0;xp=0;score=0;traits={awareness:0,confidence:0,empathy:0};$('socialArena').classList.add('open');$('socialArena').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';render()}
function close(){$('socialArena').classList.remove('open');$('socialArena').setAttribute('aria-hidden','true');document.body.style.overflow=''}
function render(){const s=scenes[idx];$('socialProgress').textContent=`${idx+1} / ${scenes.length}`;$('socialAvatar').textContent=s.avatar;$('socialPerson').textContent=s.person;$('socialContext').textContent=s.context;$('socialQuestion').textContent=s.question;$('socialSignals').innerHTML=s.signals.map(x=>`<span class="signal">${x}</span>`).join('');$('socialResult').hidden=true;$('socialSummary').hidden=true;const letters=['A','B','C','D'];$('socialChoices').hidden=false;$('socialChoices').innerHTML=s.choices.map((c,i)=>`<button class="social-choice" data-social-choice="${i}"><span class="social-letter">${letters[i]}</span><span><b>${c.t}</b><small>${c.s}</small></span></button>`).join('');$('socialChoices').querySelectorAll('[data-social-choice]').forEach(b=>b.addEventListener('click',()=>choose(+b.dataset.socialChoice)));$('socialArena').scrollTo({top:0,behavior:'smooth'})}
function choose(i){const c=scenes[idx].choices[i];score+=c.score;xp+=8+c.score*3;Object.entries(c.traits).forEach(([k,v])=>traits[k]+=v);$('socialChoices').hidden=true;$('socialResultTitle').textContent=c.out;$('socialResultText').textContent=c.text;$('socialInsight').textContent='💡 '+c.insight;$('readFill').style.width=`${c.score*25}%`;$('readScore').textContent=`${c.score}/4`;$('socialResult').hidden=false}
function next(){if(idx<scenes.length-1){idx++;render()}else summary()}
function summary(){$('socialChoices').hidden=true;$('socialResult').hidden=true;$('socialSummary').hidden=false;const maxPossible=scenes.length*4;const pct=Math.round(score/maxPossible*100);let label='Developing Reader',text='You are learning to separate evidence from assumptions.';if(pct>=85){label='Calm Social Reader';text='You consistently use context, patterns and uncertainty instead of jumping to conclusions.'}else if(pct>=65){label='Context-Aware Observer';text='Your social reads are usually balanced, with a few places where emotion can outrun evidence.'}else if(pct>=45){label='Intuitive but Reactive';text='You catch some useful signals, but single cues can still pull your interpretation too strongly.'}$('socialProfileLabel').textContent=label;$('socialProfileSummary').textContent=`${text} Accuracy: ${pct}%. Session reward: ${xp} XP.`;const max=Math.max(1,...Object.values(traits).map(v=>Math.max(0,v)));$('socialProfileBars').innerHTML=Object.entries(traits).map(([k,v])=>`<div class="social-profile-line"><span>${k.toUpperCase()}</span><div class="social-meter"><i style="width:${Math.max(4,Math.max(0,v)/max*100)}%"></i></div><b>${v}</b></div>`).join('');$('socialArena').scrollTo({top:0,behavior:'smooth'})}
function finish(){const s=readState();s.totalXP=(s.totalXP||0)+xp;s.socialSessions=(s.socialSessions||0)+1;s.socialProfile=s.socialProfile||{awareness:0,confidence:0,empathy:0};Object.entries(traits).forEach(([k,v])=>s.socialProfile[k]=(s.socialProfile[k]||0)+v);s.stats=s.stats||{};s.stats.SOC=Math.min(100,(s.stats.SOC||10)+2);s.stats.CHA=Math.min(100,(s.stats.CHA||10)+1);writeState(s);close();location.reload()}
const card=document.querySelector('[data-module="Social Arena"]');if(card){card.querySelector('em')?.remove();const badge=document.createElement('em');badge.textContent='PLAYABLE';card.appendChild(badge);card.addEventListener('click',e=>{e.stopImmediatePropagation();open()},true)}
$('closeSocial')?.addEventListener('click',close);$('nextSocial')?.addEventListener('click',next);$('finishSocial')?.addEventListener('click',finish);
})();
