(()=>{
const STORAGE_KEY='evolve-v01',DEPTH_KEY='evolve_game_depth_v1';
const baseScenes=[
 {person:'Classmate',avatar:'🙂',context:'You say something in a group and one classmate smiles, but gives only a short reply. Later they talk normally with someone else.',question:'What is the safest interpretation?',signals:['smiled','short reply','normal with others'],choices:[
  {t:'They dislike me',s:'Their short reply is proof they are avoiding me.',score:1,traits:{awareness:0,confidence:-1,empathy:0},out:'Too certain from weak evidence',text:'A short reply can mean many things. One moment is not enough to conclude rejection.',insight:'Separate facts from the story your mind adds.'},
  {t:'They may have been distracted',s:'The smile matters, and the short reply alone is ambiguous.',score:4,traits:{awareness:3,confidence:1,empathy:2},out:'Balanced read',text:'You notice the positive cue without over-reading the limited response.',insight:'Strong social reading uses multiple cues, not one isolated signal.'},
  {t:'They definitely like me',s:'The smile is a clear sign of attraction.',score:1,traits:{awareness:-1,confidence:1,empathy:0},out:'Overconfident interpretation',text:'A smile can signal friendliness, politeness, comfort or attraction. Context is still missing.',insight:'Do not upgrade a possibility into certainty.'},
  {t:'I should immediately ask what is wrong',s:'Directly confront the change before it becomes awkward.',score:2,traits:{awareness:1,confidence:2,empathy:0},out:'Direct, but premature',text:'Directness is useful when there is a pattern. Here, the evidence is still thin.',insight:'Clarity is good; timing matters too.'}
 ]},
 {person:'Friend',avatar:'🧑',context:'A close friend usually replies quickly. Today they leave your message unread for hours, then respond normally without explaining.',question:'What should you do next?',signals:['unusual delay','normal response','no conflict'],choices:[
  {t:'Act normal unless a pattern appears',s:'One unusual delay does not require a confrontation.',score:4,traits:{awareness:3,confidence:2,empathy:2},out:'Low-drama confidence',text:'You protect the friendship from unnecessary tension while staying observant.',insight:'Patterns deserve conclusions; single events usually deserve curiosity.'},
  {t:'Reply dryly to match them',s:'Show that you noticed the delay.',score:1,traits:{awareness:0,confidence:-1,empathy:-1},out:'Defensive mirroring',text:'Matching imagined distance can create the exact tension you were afraid of.',insight:'Do not punish people for explanations you invented.'},
  {t:'Ask mutual friends what happened',s:'Gather information without asking directly.',score:2,traits:{awareness:1,confidence:-1,empathy:0},out:'Indirect information gathering',text:'You may get context, but you also risk turning a small issue into group gossip.',insight:'Private uncertainty is usually best handled privately.'},
  {t:'Send several follow-up messages',s:'Make sure they did not miss your message.',score:1,traits:{awareness:0,confidence:-2,empathy:0},out:'Anxiety takes control',text:'Repeated checking can create pressure when there may be no problem at all.',insight:'Confidence often looks like tolerating temporary uncertainty.'}
 ]},
 {person:'Group project teammate',avatar:'👥',context:'During a discussion, one teammate keeps interrupting you but also interrupts everyone else. Their tone is fast, not hostile.',question:'How do you read the behaviour?',signals:['interrupts everyone','fast tone','no insults'],choices:[
  {t:'They specifically disrespect me',s:'Interrupting is a dominance move directed at me.',score:1,traits:{awareness:-1,confidence:0,empathy:0},out:'Personalized too quickly',text:'Because they interrupt everyone, the behaviour is more likely a communication habit than a targeted attack.',insight:'Compare how someone treats you with how they treat everyone else.'},
  {t:'They are probably an impulsive communicator',s:'The pattern is broad, so I can set a boundary without making it personal.',score:4,traits:{awareness:3,confidence:2,empathy:2},out:'Context-aware read',text:'You identify the pattern while still protecting your chance to speak.',insight:'Good social intelligence combines interpretation with boundaries.'},
  {t:'I should stay quiet',s:'Avoid creating tension in the group.',score:1,traits:{awareness:1,confidence:-2,empathy:1},out:'Peace at your expense',text:'Avoiding conflict can be useful, but repeatedly disappearing from the conversation is not a healthy solution.',insight:'A calm boundary is not the same thing as an argument.'},
  {t:'Interrupt them back harder',s:'Match their style so they understand.',score:2,traits:{awareness:0,confidence:2,empathy:-1},out:'Escalation instead of boundary',text:'You may get speaking space, but the group communication quality gets worse.',insight:'Assertiveness works better when it is controlled.'}
 ]},
 {person:'New person',avatar:'✨',context:'Someone you recently met asks you questions, remembers a small detail you mentioned, and starts conversations twice this week.',question:'What can you reasonably conclude?',signals:['asks questions','remembers details','initiates twice'],choices:[
  {t:'They are interested in interacting with me',s:'There is repeated engagement, but I do not need to label it further yet.',score:4,traits:{awareness:3,confidence:2,empathy:2},out:'Evidence-based confidence',text:'Repeated initiative is meaningful. You recognize interest without guessing exactly what kind.',insight:'Notice genuine positive signals without forcing a romantic or negative story.'},
  {t:'They definitely have romantic feelings',s:'Remembering details proves attraction.',score:2,traits:{awareness:0,confidence:2,empathy:0},out:'Possible, not proven',text:'Attraction is one explanation, but friendliness and curiosity also fit the evidence.',insight:'Be confident about the signal, modest about the interpretation.'},
  {t:'They are only being polite',s:'Assume nothing positive so I do not get disappointed.',score:2,traits:{awareness:0,confidence:-2,empathy:1},out:'Protective pessimism',text:'Ignoring repeated positive behaviour is also a bias.',insight:'Under-reading can distort reality just as much as over-reading.'},
  {t:'I should test them by becoming distant',s:'See whether they chase me.',score:1,traits:{awareness:-1,confidence:-1,empathy:-1},out:'Games reduce clarity',text:'Artificial distance creates noisy data and can damage a naturally developing connection.',insight:'Healthy social confidence does not need hidden tests.'}
 ]},
 {person:'Senior / authority',avatar:'🧭',context:'A senior gives you blunt feedback: “This needs more work.” They then spend ten minutes showing you what to fix.',question:'What is the strongest read?',signals:['blunt words','gives time','specific help'],choices:[
  {t:'They think I am incompetent',s:'The criticism means they have a low opinion of me.',score:1,traits:{awareness:-1,confidence:-2,empathy:0},out:'Criticism became identity',text:'The extra time and specific help are evidence that they expect improvement, not necessarily failure.',insight:'Feedback about work is not automatically a judgment of your worth.'},
  {t:'The delivery is blunt, but the intent looks constructive',s:'Use the useful information and judge the pattern over time.',score:4,traits:{awareness:3,confidence:2,empathy:2},out:'Emotionally steady read',text:'You distinguish tone from intent and keep access to useful feedback.',insight:'Social maturity means reading behaviour as a whole.'},
  {t:'I should defend every decision I made',s:'Make sure they know I had reasons.',score:2,traits:{awareness:1,confidence:1,empathy:-1},out:'Defensiveness blocks learning',text:'Explaining context can help, but defending everything makes feedback harder to use.',insight:'Confidence can absorb criticism without collapsing or fighting.'},
  {t:'I should avoid them next time',s:'Reduce chances of being criticized again.',score:1,traits:{awareness:0,confidence:-2,empathy:0},out:'Avoidance protects comfort',text:'You avoid discomfort, but also lose mentorship and information.',insight:'Growth often requires staying present through uncomfortable feedback.'}
 ]}
];
const extraScenes=[
 {person:'Quiet classmate',avatar:'😶',context:'A classmate is warm with you in person but rarely messages first. When you meet, they remember previous conversations and stay engaged.',question:'What is the most balanced read?',signals:['warm in person','rarely texts first','remembers details'],choices:[
  {t:'They are not interested in me at all',s:'If they cared, they would always initiate online.',score:1,traits:{awareness:-1,confidence:-1,empathy:0},out:'One channel became the whole story',text:'People differ a lot in messaging habits. In-person behaviour carries useful evidence too.',insight:'Do not judge an entire relationship through one communication style.'},
  {t:'They likely value the interaction, but may not be an initiator online',s:'The in-person consistency matters more than one habit.',score:4,traits:{awareness:3,confidence:2,empathy:2},out:'Multi-channel read',text:'You combine the different signals instead of forcing them into a simple yes/no story.',insight:'Social evidence should be weighted, not merely counted.'},
  {t:'They are secretly testing me',s:'They want to see if I will chase them.',score:1,traits:{awareness:-1,confidence:0,empathy:-1},out:'Hidden motive invented',text:'There is no evidence of a test. Adding secret motives makes the situation noisier.',insight:'Prefer the simplest explanation that fits the evidence.'},
  {t:'I should stop initiating completely',s:'Make them prove they care.',score:2,traits:{awareness:0,confidence:-1,empathy:-1},out:'Clarity replaced by a test',text:'Pulling away may create distance without actually teaching you anything useful.',insight:'Consistency is usually more informative than games.'}
 ]},
 {person:'Friend group',avatar:'🫂',context:'You enter a group conversation and the topic changes soon after. Nobody excludes you directly, and two people still respond when you speak.',question:'What should you avoid assuming?',signals:['topic changed','some responses','no direct exclusion'],choices:[
  {t:'The group changed topic because of me',s:'My arrival probably killed the mood.',score:1,traits:{awareness:-1,confidence:-2,empathy:0},out:'Self-focused interpretation',text:'Conversation topics change constantly. The available evidence does not support making yourself the cause.',insight:'Not every social shift is about you.'},
  {t:'There is not enough evidence to personalize the change',s:'I should observe the broader pattern first.',score:4,traits:{awareness:3,confidence:2,empathy:2},out:'Grounded interpretation',text:'You resist making yourself the center of an ambiguous event.',insight:'Uncertainty is not the same as rejection.'},
  {t:'They are fake friends',s:'Real friends would keep the same topic.',score:1,traits:{awareness:-1,confidence:-1,empathy:-1},out:'Escalated conclusion',text:'A routine conversational change became a judgment about the whole friendship.',insight:'Big conclusions need big evidence.'},
  {t:'I should leave immediately',s:'Protect myself from being unwanted.',score:2,traits:{awareness:0,confidence:-2,empathy:0},out:'Withdrawal before clarity',text:'Leaving may protect you from discomfort, but it can also reinforce a false interpretation.',insight:'Stay long enough to gather better evidence.'}
 ]},
 {person:'Teammate',avatar:'🧩',context:'A teammate disagrees with your idea strongly in the meeting, but later sends you a useful suggestion privately and credits one of your earlier points.',question:'What is the best interpretation?',signals:['public disagreement','private help','credits your point'],choices:[
  {t:'They are trying to undermine me',s:'Public disagreement means they are against me.',score:1,traits:{awareness:-1,confidence:-1,empathy:0},out:'Disagreement became hostility',text:'The later help and credit suggest they can disagree with the idea without rejecting you.',insight:'Separate disagreement about content from rejection of the person.'},
  {t:'They seem willing to challenge ideas while still cooperating',s:'The full pattern is competitive but constructive.',score:4,traits:{awareness:3,confidence:2,empathy:2},out:'Nuanced team read',text:'You notice both friction and cooperation instead of flattening the situation.',insight:'Healthy teams can contain disagreement and respect at the same time.'},
  {t:'They must secretly agree with me',s:'The private message proves the public disagreement was fake.',score:2,traits:{awareness:0,confidence:1,empathy:0},out:'Over-corrected interpretation',text:'They can still disagree overall while valuing parts of your thinking.',insight:'Mixed signals often mean mixed realities, not hidden certainty.'},
  {t:'I should confront them about embarrassing me',s:'Public disagreement deserves a direct response.',score:2,traits:{awareness:1,confidence:2,empathy:-1},out:'Potentially valid, but premature',text:'If the tone was disrespectful, a boundary may matter. But disagreement itself is not enough.',insight:'Read intent and delivery separately.'}
 ]},
 {person:'Someone you like',avatar:'🌙',context:'They are friendly, smile often, and sometimes seek you out. But they behave similarly with several other people too.',question:'What is the strongest conclusion you can make?',signals:['friendly','sometimes initiates','similar with others'],choices:[
  {t:'They definitely like me romantically',s:'The smiles and initiative are enough proof.',score:1,traits:{awareness:-1,confidence:1,empathy:0},out:'Positive cues over-interpreted',text:'The behaviour is genuinely warm, but because it is broad, the romantic meaning is still uncertain.',insight:'Positive does not automatically mean exclusive.'},
  {t:'They seem comfortable and positive with me; anything beyond that is still uncertain',s:'Recognize the good signal without forcing a label.',score:4,traits:{awareness:3,confidence:2,empathy:2},out:'Confident without fantasy',text:'You neither dismiss the warmth nor convert it into certainty.',insight:'The strongest social reads preserve both evidence and uncertainty.'},
  {t:'It means nothing',s:'If they act that way with others, there is no positive signal at all.',score:2,traits:{awareness:0,confidence:-2,empathy:1},out:'Under-reading the positive',text:'General friendliness does not erase the fact that they are also comfortable with you.',insight:'Avoid both wishful thinking and defensive pessimism.'},
  {t:'I should make them jealous to test it',s:'Their reaction would reveal the truth.',score:1,traits:{awareness:-1,confidence:-1,empathy:-2},out:'Manipulation creates bad data',text:'Jealousy tests can damage trust and produce reactions for many reasons.',insight:'Clear behaviour creates clearer evidence than manipulation.'}
 ]},
 {person:'Lecturer / manager',avatar:'📋',context:'They are noticeably more formal with you than with a few others, but consistently answer your questions, give detailed instructions, and include you in important tasks.',question:'What is the most reliable read?',signals:['formal tone','responsive','trusted with tasks'],choices:[
  {t:'They dislike me',s:'Formality means emotional distance.',score:1,traits:{awareness:-1,confidence:-1,empathy:0},out:'Tone outweighed behaviour',text:'Their actions show reliability and inclusion even if their style with you is formal.',insight:'Behavioural investment often matters more than warmth of tone.'},
  {t:'Their style with me is formal, but their behaviour shows professional trust',s:'Use actions as stronger evidence than warmth alone.',score:4,traits:{awareness:3,confidence:2,empathy:2},out:'Action-weighted read',text:'You distinguish interpersonal style from actual treatment.',insight:'Trust can look serious rather than friendly.'},
  {t:'They are scared of me',s:'Formality usually means intimidation.',score:1,traits:{awareness:-1,confidence:1,empathy:0},out:'Speculation without support',text:'There is no evidence for fear. The same behaviour fits professionalism much better.',insight:'Do not choose dramatic explanations when ordinary ones fit.'},
  {t:'I should become extra casual to break the formality',s:'Force the relationship to feel warmer.',score:2,traits:{awareness:1,confidence:1,empathy:0},out:'May ignore context',text:'Warmth can grow naturally, but forcing informality can misread a professional boundary.',insight:'Respect the relationship you actually have.'}
 ]}
];
let sessionScenes=[],idx=0,xp=0,score=0,traits={awareness:0,confidence:0,empathy:0};
const $=id=>document.getElementById(id);
function readState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{}}catch{return{}}}
function writeState(s){localStorage.setItem(STORAGE_KEY,JSON.stringify(s))}
function depth(){try{return JSON.parse(localStorage.getItem(DEPTH_KEY)||'{}').social?.plays||0}catch{return 0}}
function shuffled(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function buildSession(){const plays=depth();let pool=[...baseScenes];if(plays>=2)pool.push(...extraScenes.slice(0,2));if(plays>=5)pool.push(...extraScenes);sessionScenes=shuffled(pool).slice(0,5)}
function open(){buildSession();idx=0;xp=0;score=0;traits={awareness:0,confidence:0,empathy:0};$('socialArena').classList.add('open');$('socialArena').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';render()}
function close(){$('socialArena').classList.remove('open');$('socialArena').setAttribute('aria-hidden','true');document.body.style.overflow=''}
function render(){const s=sessionScenes[idx];$('socialProgress').textContent=`${idx+1} / ${sessionScenes.length}`;$('socialAvatar').textContent=s.avatar;$('socialPerson').textContent=s.person;$('socialContext').textContent=s.context;$('socialQuestion').textContent=s.question;$('socialSignals').innerHTML=s.signals.map(x=>`<span class="signal">${x}</span>`).join('');$('socialResult').hidden=true;$('socialSummary').hidden=true;const letters=['A','B','C','D'];$('socialChoices').hidden=false;const choices=shuffled(s.choices);$('socialChoices').innerHTML=choices.map((c,i)=>`<button class="social-choice" data-social-choice="${i}"><span class="social-letter">${letters[i]}</span><span><b>${c.t}</b><small>${c.s}</small></span></button>`).join('');$('socialChoices').querySelectorAll('[data-social-choice]').forEach(b=>b.addEventListener('click',()=>choose(+b.dataset.socialChoice,choices)));$('socialArena').scrollTo({top:0,behavior:'smooth'})}
function choose(i,choices){const c=choices[i];score+=c.score;xp+=8+c.score*3;Object.entries(c.traits).forEach(([k,v])=>traits[k]+=v);$('socialChoices').hidden=true;$('socialResultTitle').textContent=c.out;$('socialResultText').textContent=c.text;$('socialInsight').textContent='💡 '+c.insight;$('readFill').style.width=`${c.score*25}%`;$('readScore').textContent=`${c.score}/4`;$('socialResult').hidden=false}
function next(){if(idx<sessionScenes.length-1){idx++;render()}else summary()}
function summary(){$('socialChoices').hidden=true;$('socialResult').hidden=true;$('socialSummary').hidden=false;const maxPossible=sessionScenes.length*4;const pct=Math.round(score/maxPossible*100);let label='Developing Reader',text='You are learning to separate evidence from assumptions.';if(pct>=85){label='Calm Social Reader';text='You consistently use context, patterns and uncertainty instead of jumping to conclusions.'}else if(pct>=65){label='Context-Aware Observer';text='Your social reads are usually balanced, with a few places where emotion can outrun evidence.'}else if(pct>=45){label='Intuitive but Reactive';text='You catch some useful signals, but single cues can still pull your interpretation too strongly.'}$('socialProfileLabel').textContent=label;$('socialProfileSummary').textContent=`${text} Accuracy: ${pct}%. Session reward: ${xp} XP.`;const max=Math.max(1,...Object.values(traits).map(v=>Math.max(0,v)));$('socialProfileBars').innerHTML=Object.entries(traits).map(([k,v])=>`<div class="social-profile-line"><span>${k.toUpperCase()}</span><div class="social-meter"><i style="width:${Math.max(4,Math.max(0,v)/max*100)}%"></i></div><b>${v}</b></div>`).join('');$('socialArena').scrollTo({top:0,behavior:'smooth'})}
function finish(){const s=readState();s.totalXP=(s.totalXP||0)+xp;s.socialSessions=(s.socialSessions||0)+1;s.socialProfile=s.socialProfile||{awareness:0,confidence:0,empathy:0};Object.entries(traits).forEach(([k,v])=>s.socialProfile[k]=(s.socialProfile[k]||0)+v);s.stats=s.stats||{};s.stats.SOC=Math.min(100,(s.stats.SOC||10)+2);s.stats.CHA=Math.min(100,(s.stats.CHA||10)+1);writeState(s);close();location.reload()}
const card=document.querySelector('[data-module="Social Arena"]');if(card){card.querySelector('em')?.remove();const badge=document.createElement('em');badge.textContent='PLAYABLE';card.appendChild(badge);card.addEventListener('click',e=>{e.stopImmediatePropagation();open()},true)}
$('closeSocial')?.addEventListener('click',close);$('nextSocial')?.addEventListener('click',next);$('finishSocial')?.addEventListener('click',finish);
})();
